// -*- C++ -*-
//
// generated by wxGlade 1.0.0 on Tue Aug 10 20:20:50 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef AIOPANEL_H
#define AIOPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class AioPanel: public wxPanel {
public:
  // begin wxGlade: AioPanel::ids
  enum {
    aesSyncID = wxID_HIGHEST + 1000,
    spdifSyncID = wxID_HIGHEST + 1001,
    adatSyncID = wxID_HIGHEST + 1002,
    tcoSyncID = wxID_HIGHEST + 1003,
    syncInSyncID = wxID_HIGHEST + 1004,
    pitchID = wxID_HIGHEST + 1005,
    inputLevelID = wxID_HIGHEST + 1006,
    spdifInID = wxID_HIGHEST + 1007,
    outputLevelID = wxID_HIGHEST + 1008,
    spdifOpticalID = wxID_HIGHEST + 1009,
    spdifProID = wxID_HIGHEST + 1010,
    tmsID = wxID_HIGHEST + 1011,
    phonesLevelID = wxID_HIGHEST + 1012,
    analogOutID = wxID_HIGHEST + 1013,
    singleSpeedWclkID = wxID_HIGHEST + 1014,
  };
  // end wxGlade

  AioPanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
  // begin wxGlade: AioPanel::attributes
  wxStaticText* clockSourceLabel_2;
  wxStaticText* sampleRateLabel_2;
  wxStaticText* bufferSizeLabel_2;
  wxRadioButton* masterButton;
  wxStaticText* internalFreqLabel;
  wxChoice* internalFreqChoice;
  wxStaticBitmap* internalWarn;
  wxRadioButton* wclkSyncButton;
  wxStaticText* wclkStatusLabel;
  wxStaticText* wclkFreqLabel;
  wxStaticBitmap* wclkWarn;
  wxRadioButton* aesSyncButton;
  wxStaticText* aesStatusLabel;
  wxStaticText* aesFreqLabel;
  wxStaticBitmap* aesWarn;
  wxRadioButton* spdifSyncButton;
  wxStaticText* spdifStatusLabel;
  wxStaticText* spdifFreqLabel;
  wxStaticBitmap* spdifWarn;
  wxRadioButton* adatSyncButton;
  wxStaticText* adatStatusLabel;
  wxStaticText* adatFreqLabel;
  wxStaticBitmap* adatWarn;
  wxRadioButton* tcoSyncButton;
  wxStaticText* tcoStatusLabel;
  wxStaticText* tcoFreqLabel;
  wxStaticBitmap* tcoWarn;
  wxRadioButton* syncInSyncButton;
  wxStaticText* syncInStatusLabel;
  wxStaticText* syncInFreqLabel;
  wxStaticBitmap* syncInWarn;
  wxSlider* pitchSlider;
  wxRadioBox* inputLevelBox;
  wxRadioBox* spdifInBox;
  wxRadioBox* outputLevelBox;
  wxCheckBox* spdifOpticalButton;
  wxCheckBox* spdifProButton;
  wxCheckBox* tmsButton;
  wxRadioBox* phonesLevelBox;
  wxRadioBox* analogOutBox;
  wxCheckBox* singleSpeedWclkButton;
  wxCheckBox* aebiPresentCheckBox;
  wxCheckBox* aeboPresentCheckBox;
  wxCheckBox* tcoPresentCheckBox;
  wxStaticText* fwVersionLabel;
  // end wxGlade

  DECLARE_EVENT_TABLE();

public:
  virtual void setMasterMode(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void aesSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adatSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tcoSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void syncInSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void pitchChangedCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchDownCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchUpCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchPrevCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchNextCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchSliderCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void inputLevelCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifInCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void outputLevelCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifOpticalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifProfessionalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tmsCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void phonesLevelCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void analogOutCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void singleSpeedWclkOutCB(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // AIOPANEL_H
