// -*- C++ -*-
//
// generated by wxGlade 1.0.3 on Tue Dec  7 21:50:43 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef MADIPANEL_H
#define MADIPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class MADIPanel: public wxPanel {
public:
  // begin wxGlade: MADIPanel::ids
  enum {
    masterID = wxID_HIGHEST + 1000,
    wclkSyncID = wxID_HIGHEST + 1001,
    madiSyncID = wxID_HIGHEST + 1002,
    tcoSyncID = wxID_HIGHEST + 1003,
    syncInSyncID = wxID_HIGHEST + 1004,
    pitchID = wxID_HIGHEST + 1005,
    madiInputID = wxID_HIGHEST + 1006,
    autoselectInputID = wxID_HIGHEST + 1007,
    tx64chID = wxID_HIGHEST + 1008,
    doubleWireID = wxID_HIGHEST + 1009,
    singleSpeedWclkID = wxID_HIGHEST + 1010,
    tmsID = wxID_HIGHEST + 1011,
    currentMadiInputBoxID = wxID_HIGHEST + 1012,
    rx64chID = wxID_HIGHEST + 1013,
  };
  // end wxGlade

  MADIPanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
  // begin wxGlade: MADIPanel::attributes
  wxStaticText* clockSourceLabel;
  wxStaticText* sampleRateLabel;
  wxStaticText* bufferSizeLabel;
  wxStaticText* fwVersionLabel;
  wxRadioButton* masterButton;
  wxStaticText* internalFreqLabel;
  wxChoice* internalFreqChoice;
  wxStaticBitmap* internalWarn;
  wxRadioButton* wclkSyncButton;
  wxStaticText* wclkStatusLabel;
  wxStaticText* wclkFreqLabel;
  wxStaticBitmap* wclkWarn;
  wxRadioButton* madiSyncButton;
  wxStaticText* madiStatusLabel;
  wxStaticText* madiFreqLabel;
  wxStaticBitmap* madiWarn;
  wxRadioButton* tcoSyncButton;
  wxStaticText* tcoStatusLabel;
  wxStaticText* tcoFreqLabel;
  wxStaticBitmap* tcoWarn;
  wxRadioButton* syncInSyncButton;
  wxStaticText* syncInStatusLabel;
  wxStaticText* syncInFreqLabel;
  wxStaticBitmap* syncInWarn;
  wxSlider* pitchSlider;
  wxRadioBox* madiInputBox;
  wxCheckBox* autoselectInputButton;
  wxCheckBox* tx64chButton;
  wxCheckBox* doubleWireButton;
  wxCheckBox* singleSpeedWclkButton;
  wxCheckBox* tmsButton;
  wxRadioBox* currentMadiInputBox;
  wxCheckBox* rx64chButton;
  // end wxGlade

  DECLARE_EVENT_TABLE();

public:
  virtual void masterCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void internalFreqCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void wclkSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void madiSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tcoSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void syncInSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void pitchDownCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchUpCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchPrevCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchNextCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchSliderCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void madiInputCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void autoselectInputCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tx64chCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void doubleWireCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void singleSpeedWclkOutCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tmsCB(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // MADIPANEL_H
