// -*- C++ -*-
//
// generated by wxGlade 1.0.0 on Tue Aug 10 18:59:00 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef NOCARDSPANEL_H
#define NOCARDSPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class NoCardsPanel: public wxPanel {
public:
  // begin wxGlade: NoCardsPanel::ids
  // end wxGlade

  NoCardsPanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
  // begin wxGlade: NoCardsPanel::attributes
  // end wxGlade
}; // wxGlade: end class


#endif // NOCARDSPANEL_H
