// -*- C++ -*-
//
// generated by wxGlade 1.0.3 on Sat Nov 20 16:07:22 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef RAYDATPANEL_H
#define RAYDATPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class RayDATPanel: public wxPanel {
public:
  // begin wxGlade: RayDATPanel::ids
  enum {
    masterID = wxID_HIGHEST + 1000,
    wclkSyncID = wxID_HIGHEST + 1001,
    aesSyncID = wxID_HIGHEST + 1002,
    spdifSyncID = wxID_HIGHEST + 1003,
    adat1SyncID = wxID_HIGHEST + 1004,
    adat2SyncID = wxID_HIGHEST + 1005,
    adat3SyncID = wxID_HIGHEST + 1006,
    adat4SyncID = wxID_HIGHEST + 1007,
    tcoSyncID = wxID_HIGHEST + 1008,
    syncInSyncID = wxID_HIGHEST + 1009,
    pitchID = wxID_HIGHEST + 1010,
    spdifInID = wxID_HIGHEST + 1011,
    spdifOpticalID = wxID_HIGHEST + 1012,
    spdifProID = wxID_HIGHEST + 1013,
    tmsID = wxID_HIGHEST + 1014,
    adat1InternalID = wxID_HIGHEST + 1015,
    adat2InternalID = wxID_HIGHEST + 1016,
    singleSpeedWclkID = wxID_HIGHEST + 1017,
  };
  // end wxGlade

  RayDATPanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
  // begin wxGlade: RayDATPanel::attributes
  wxStaticText* clockSourceLabel;
  wxStaticText* sampleRateLabel;
  wxStaticText* bufferSizeLabel;
  wxStaticText* fwVersionLabel;
  wxRadioButton* masterButton;
  wxStaticText* internalFreqLabel;
  wxChoice* internalFreqChoice;
  wxStaticBitmap* internalWarn;
  wxRadioButton* wclkSyncButton;
  wxStaticText* wclkStatusLabel;
  wxStaticText* wclkFreqLabel;
  wxStaticBitmap* wclkWarn;
  wxRadioButton* aesSyncButton;
  wxStaticText* aesStatusLabel;
  wxStaticText* aesFreqLabel;
  wxStaticBitmap* aesWarn;
  wxRadioButton* spdifSyncButton;
  wxStaticText* spdifStatusLabel;
  wxStaticText* spdifFreqLabel;
  wxStaticBitmap* spdifWarn;
  wxRadioButton* adat1SyncButton;
  wxStaticText* adat1StatusLabel;
  wxStaticText* adat1FreqLabel;
  wxStaticBitmap* adat1Warn;
  wxRadioButton* adat2SyncButton;
  wxStaticText* adat2StatusLabel;
  wxStaticText* adat2FreqLabel;
  wxStaticBitmap* adat2Warn;
  wxRadioButton* adat3SyncButton;
  wxStaticText* adat3StatusLabel;
  wxStaticText* adat3FreqLabel;
  wxStaticBitmap* adat3Warn;
  wxRadioButton* adat4SyncButton;
  wxStaticText* adat4StatusLabel;
  wxStaticText* adat4FreqLabel;
  wxStaticBitmap* adat4Warn;
  wxRadioButton* tcoSyncButton;
  wxStaticText* tcoStatusLabel;
  wxStaticText* tcoFreqLabel;
  wxStaticBitmap* tcoWarn;
  wxRadioButton* syncInSyncButton;
  wxStaticText* syncInStatusLabel;
  wxStaticText* syncInFreqLabel;
  wxStaticBitmap* syncInWarn;
  wxSlider* pitchSlider;
  wxRadioBox* spdifInBox;
  wxCheckBox* spdifOpticalButton;
  wxCheckBox* spdifProButton;
  wxCheckBox* tmsButton;
  wxCheckBox* adat1InternalButton;
  wxCheckBox* adat2InternalButton;
  wxCheckBox* singleSpeedWclkButton;
  // end wxGlade

  DECLARE_EVENT_TABLE();

public:
  virtual void masterCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void internalFreqCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void wclkSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void aesSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat1SyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat2SyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat3SyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat4SyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tcoSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void syncInSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void pitchDownCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchUpCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchPrevCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchNextCB(wxScrollEvent &event); // wxGlade: <event_handler>
  virtual void pitchSliderCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifInCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifOpticalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void spdifProfessionalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void tmsCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat1InternalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void adat2InternalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void singleSpeedWclkOutCB(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // RAYDATPANEL_H
