// -*- C++ -*-
//
// generated by wxGlade 1.0.0 on Mon Oct 18 22:26:57 2021
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef TCOPANEL_H
#define TCOPANEL_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class TCOPanel: public wxPanel {
public:
  // begin wxGlade: TCOPanel::ids
  enum {
    ltcSyncID = wxID_HIGHEST + 1000,
    videoSyncID = wxID_HIGHEST + 1001,
    wckSyncID = wxID_HIGHEST + 1002,
    termID = wxID_HIGHEST + 1003,
    ltcFrameRateID = wxID_HIGHEST + 1004,
    dropFrameID = wxID_HIGHEST + 1005,
    wckConversionID = wxID_HIGHEST + 1006,
    ltcSampleRateID = wxID_HIGHEST + 1007,
    pullID = wxID_HIGHEST + 1008,
    useTcoID = wxID_HIGHEST + 1009,
    autoID = wxID_HIGHEST + 1010,
    positionalID = wxID_HIGHEST + 1011,
    wallClockID = wxID_HIGHEST + 1012,
    jamSyncID = wxID_HIGHEST + 1013,
    runID = wxID_HIGHEST + 1014,
  };
  // end wxGlade

  TCOPanel(wxWindow* parent, wxWindowID id, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=0);

private:

protected:
  // begin wxGlade: TCOPanel::attributes
  wxRadioButton* ltcSyncButton;
  wxStaticText* ltcStatusLabel;
  wxStaticText* ltcInFrameRateLabel;
  wxRadioButton* videoSyncButton;
  wxStaticText* videoStatusLabel;
  wxRadioButton* wckSyncButton;
  wxStaticText* wckStatusLabel;
  wxCheckBox* termButton;
  wxRadioBox* ltcFrameRateBox;
  wxCheckBox* dropFrameButton;
  wxRadioBox* wckConversionBox;
  wxRadioBox* ltcSampleRateBox;
  wxRadioBox* pullBox;
  wxCheckBox* useTCOButton;
  wxStaticText* sampleRateLabel;
  wxStaticText* lockLabel;
  wxButton* autoButton;
  wxButton* positionalButton;
  wxButton* wallClockButton;
  wxButton* jamSyncButton;
  wxCheckBox* ltcRunButton;
  // end wxGlade

  DECLARE_EVENT_TABLE();

public:
  virtual void ltcSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void videoSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void wckSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void termCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void ltcFrameRateCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void dropFrameCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void wckConversionCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void ltcSampleRateCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void pullCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void useTcoCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void autoCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void positionalCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void wallClockCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void jamSyncCB(wxCommandEvent &event); // wxGlade: <event_handler>
  virtual void ltcRunCB(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // TCOPANEL_H
